[NezhaMonitoring]
other = "Nezha Monitoring"

[Server]
other = "Servers"

[Services]
other = "Services"

[Task]
other = "Tasks"

[Notification]
other = "Notifications"

[Settings]
other = "Settings"

[Home]
other = "Home"

[BackToHomepage]
other = "Back to Homepage"

[AdminPanel]
other = "Admin Panel"

[Logout]
other = "Logout"

[Login]
other = "Login"

[ConfirmLogout]
other = "Do you want to Logout?"

[AfterLoggingOutYouHaveToLoginAgain]
other = "You need to Login again to continue"

[Cancel]
other = "Cancel"

[Confirm]
other = "Confirm"

[AddScheduledTasks]
other = "Add Schedule Task"

[Name]
other = "Name"

[Scheduler]
other = "Cron Expression"

[BackUp]
other = "Backup"

[3amDaily]
other = "(Daily at 3 AM)"

[Command]
other = "Command"

[Coverage]
other = "Coverage"

[IgnoreAllAndExecuteOnlyThroughSpecificServers]
other = "Ignore All, Execute Only on Specific Servers"

[AllIncludedOnlySpecificServersAreNotExecuted]
other = "Cover All, Except Specific Servers"

[ExecuteByTriggerServer]
other = "Execute on Trigger Server"

[SpecificServers]
other = "Specific Servers"

[EnterIdAndNameToSearch]
other = "Enter ID/Name to search"

[NotificationMethodGroup]
other = "Notification Method Group"

[PushSuccessMessages]
other = "Send Success Messages"

[TaskType]
other = "Task Type"

[CronTask]
other = "Cron Task"

[TriggerTask]
other = "Trigger Task"

[TheFormaOfTheScheduleIs]
other = "The Cron Expression is like:"

[SecondsMinutesHoursDaysMonthsWeeksSeeDetails]
other = "Sec Min Hour Day Month Week, see details in "

[ScheduleExpressionFormat]
other = "CRON Expression Format"

[IntroductionOfCommands]
other = "Introduction of Commands: Writing commands is similar to shell/bat scripts. It's advised not to break lines, and multiple commands can be connected with <code>&&</code> or <code>&</code>. If a command cannot be found, it might be due to <code>PATH</code> environment variable configuration issues. On <code>Linux</code> servers, you can add <code>source ~/.bashrc</code> at the beginning of the command, or use the command's absolute path."

[AddMonitor]
other = "Add Service Monitor"

[Blog]
other = "Blog"

[Target]
other = "Target"

[Type]
other = "Type"

[SslExpirationOrChange]
other = "(SSL Expiration or Change)"

[Duration]
other = "Interval"

[Seconds]
other = "Seconds"

[EnableFailureNotification]
other = "Enable Failure Notification"

[FailureNotification]
other = "Failure Notification"

[MaxLatency]
other = "Max Latency (ms)"

[MinLatency]
other = "Min Latency (ms)"

[EnableLatencyNotification]
other = "Enable Latency Notification"

[LatencyNotification]
other = "Latency Notification"

[IntroductionOfMonitor]
other = """
For type <b>HTTP-GET</b>, enter URL (with http/https, HTTPS protocol will also monitor SSL certificate);<br>
For type <b>ICMP-Ping</b>, enter domain/IP without port: example.com;<br>
For type <b>TCP-Ping</b>, enter domain/IP + port number: example.com:22"""

[AddNotificationMethod]
other = "Add Notification Method"

[Tag]
other = "Notification Group"

[DoNotSendTestMessages]
other = "Do Not Send Test Message"

[RequestMethod]
other = "Request Method"

[RequestType]
other = "Request Type"

[VerifySSL]
other = "Verify SSL"

[AddNotificationRule]
other = "Add Notification Rule"

[Rules]
other = "Rules"

[NotificationTriggerMode]
other = "Notification Trigger Mode"

[ModeAlwaysTrigger]
other = "Always Trigger"

[ModeOnetimeTrigger]
other = "Always Trigger"

[EnableTriggerTask]
other = "Enable Trigger Task"

[FailTriggerTasks]
other = "Tasks triggered during an alarm"

[RecoverTriggerTasks]
other = "Tasks triggered during recovery"

[Enable]
other = "Enable"

[AddServer]
other = "Add Server"

[BatchEditServerGroup]
other = "Batch Edit Server Group"

[BatchDeleteServer]
other = "Batch Delete Server"

[InputServerGroupName]
other = "Input Server Group Name"

[ServerGroup]
other = "Server Group"

[EinsteinLightspeed1]
other = "Einstein Lightspeed 1"

[DisplayIndex]
other = "Display Index"

[TheLargerTheNumberTheHigherThePriority]
other = "Higher Number, Higher Priority"

[Secret]
other = "Secret"

[Note]
other = "Note"

[LinuxOneKeyInstall]
other = "Linux One-Command Install"

[NoDomainAlert]
other = "Set CDN bypassed Domain/IP in setting before using this function"

[PushSuccessfully]
other = "Send Success Notification"

[LastExecution]
other = "Last Execution"

[LastResult]
other = "Last Result"

[Administration]
other = "Manage"

[CoverAll]
other = "Cover All"

[IgnoreAll]
other = "Ignore All"

[ByTrigger]
other = "Execute by Trigger"

[DeleteScheduledTask]
other = "Delete Scheduled Task"

[ConfirmToDeleteThisScheduledTask]
other = "Are you sure you want to Delete?"

[AccessDenied]
other = "Access Denied"

[Use]
other = "Use"

[AccountToLogin]
other = "Account Login"

[SignUp]
other = "Sign up"

[DontHaveAnAccount]
other = "Don't Have an Account?"

[SSLCertificate]
other = "HTTP(S)/SSL Certificate"

[TCPPort]
other = "TCP Port"

[DeleteService]
other = "Remove Service Monitor"

[ConfirmToDeleteThisService]
other = "Confirm to Delete This Service?"

[DeleteNotificationMethod]
other = "Delete Notification Method"

[ConfirmToDeleteThisNotificationMethod]
other = "Confirm to Delete This Notification Method?"

[ForceUpdate]
other = "Force to Update"

[SelectAll]
other = "Select All"

[VersionNumber]
other = "Version"

[OneKeyInstall]
other = "One-Command Install"

[ClickToCopy]
other = "Click To Copy"

[DeleteServer]
other = "Delete Server"

[ConfirmToDeleteServer]
other = "Confirm to Delete Server?"

[NoServerSelected]
other = "No Server Selected"

[ExecutionResults]
other = "Execute Results"

[SiteTitle]
other = "Site Title"

[AdministratorList]
other = "Administrator List"

[Theme]
other = "Frontend Theme"

[CustomCodes]
other = "Custom Codes (Style and Script)"

[AccessPassword]
other = "Frontend Access Password"

[PanelServerDomainAndIP]
other = "Dashboard Server Domain/IP without CDN"

[IPChangeAlert]
other = "IP Change Notification"

[AllIncludedOnlySpecificServersAreNotAlerted]
other = "Cover All, Only ignore Specific Servers"

[IgnoreAllOnlyAlertSpecificServers]
other = "Ignore All, Cover only Specific Servers"

[IgnoreAllRequestOnlyThroughSpecificServers]
other = "Ignore All, Request Only Through Specific Servers"

[AllIncludedOnlySpecificServersAreNotRequest]
other = "Cover All, Only Specific Servers do not request."

[ServerIDSeparatedByCommas]
other = "Server IDs Separated by Commas"

[IPChangeNotificationTag]
other = "Send Notification To Specific Notification Group"

[NotificationMessagesDoNotHideIP]
other = "Show Full IP Address in Notification Messages"

[Save]
other = "Save"

[ModifiedSuccessfully]
other = "Modified successfully"

[TerminalConnectionTimeOutOrSessionEnded]
other = "Terminal Connection Timeout or Session Ended"

[TerminalConnectionFailed]
other = "The terminal connection failed. Please check the WebSocket reverse proxy configuration for /terminal/*."

[Default]
other = "Default"

[Offline]
other = "Offline"

[Platform]
other = "System"

[DiskUsed]
other = "Disk"

[MemUsed]
other = "RAM"

[CpuUsed]
other = "CPU"

[Virtualization]
other = "Virtualization"

[SwapUsed]
other = "Swap"

[NetTransfer]
other = "Usage"

[Load]
other = "Load"

[ProcessCount]
other = "Process Count"

[ConnCount]
other = "Connection Count"

[BootTime]
other = "Boot Time"

[LastActive]
other = "Last Active"

[Version]
other = "Version"

[NetSpeed]
other = "NIC"

[Uptime]
other = "Uptime"

[ServerIsOffline]
other = "Server is Offline"

[Day]
other = "Days"

[RealtimeChannelEstablished]
other = "Realtime Channel Established"

[GetTheLatestMonitoringDataInRealTime]
other = "You Can Get the Latest Monitoring Data in Real Time!"

[RealtimeChannelDisconnect]
other = "Realtime Channel Disconnect"

[CanNotGetTheLatestMonitoringDataInRealTime]
other = "Cannot Get the Latest Monitoring Data in Real Time!"

[30DaysOnline]
other = "30-Day Availability"

[Details]
other = "Details"

[Status]
other = "Status"

[Availability]
other = "Availability"

[AverageLatency]
other = "Average Latency"

[CycleTransferStats]
other = "Periodic Transfer Stats"

[From]
other = "From"

[To]
other = "To"

[NextCheck]
other = "Next check"

[CurrentUsage]
other = "Current Usage"

[VerifyPassword]
other = "Please enter your password"

[LightMode]
other = "Light Mode"

[DarkMode]
other = "Dark Mode"

[FollowSystem]
other = "System Auto"

[GridLayout]
other = "Grid Layout"

[ListLayout]
other = "List Layout"

[EnterPassword]
other = "Enter Password"

[Location]
other = "Location"

[Running]
other = "Running"

[UpNetTransfer]
other = "Outbound"

[DownNetTransfer]
other = "Inbound"

[TotalUpNetTransfer]
other = "Total Outbound"

[TotalDownNetTransfer]
other = "Total Inbound"

[WrongPassword]
other = "Incorrect Password"

[AnErrorEccurred]
other = "An Error Occurred"

[SystemError]
other = "System Error"

[NetworkError]
other = "Network Error"

[ServicesStatus]
other = "Services Status"

[ServersManagement]
other = "Servers"

[ServicesManagement]
other = "Services"

[ScheduledTasks]
other = "Scheduled Tasks"

[ApiManagement]
other = "API Management"

[IssueNewApiToken]
other = "Issue New API Token"

[Token]
other = "Token"

[DeleteToken]
other = "Delete Token"

[ConfirmToDeleteThisToken]
other = "Confirm to Delete This Token?"

[YouAreNotAuthorized]
other = "Not Authorized for This Page"

[WrongAccessPassword]
other = "Wrong Access Password"

[Add]
other = "Add"

[Edit]
other = "Edit"

[AlarmRule]
other = "Alarm Rule"

[NotificationMethod]
other = "Notification Method"

[Incident]
other = "Incident"

[Resolved]
other = "Resolved"

[StatusDown]
other = "Down"

[StatusNoData]
other = "No Data"

[StatusGood]
other = "Good"

[StatusLowAvailability]
other = "Low Availability"

[ScheduledTaskExecutedSuccessfully]
other = "Scheduled Task Executed Successfully"

[ScheduledTaskExecutedFailed]
other = "Scheduled Task Execution Failed"

[IPChanged]
other = "IP Changed"

[Transleft]
other = "Remaining Data"

[DashboardTheme]
other = "Admin Panel Theme"

[Info]
other = "Info"

[HideForGuest]
other = "Hide for Guest"

[Menu]
other = "Menu"

[NetworkSpiter]
other = "Network"

[EnableShowInService]
other = "Enable Show in Service"

[EnableDDNS]
other = "Enable DDNS"

[EnableIPv4]
other = "Enable DDNS IPv4"

[EnableIpv6]
other = "Enable DDNS IPv6"

[DDNSDomain]
other = "DDNS Domain"

[DDNSProfile]
other = "DDNS Profile Name"

[Feature]
other = "Feature"

[Template]
other = "Template"

[Stat]
other = "Asset"

[Temperature]
other = "Temperature"

[DisableSwitchTemplateInFrontend]
other = "Disable Switch Template in Frontend"

[ServersOnWorldMap]
other = "Servers On World Map"
