[NezhaMonitoring]
other = "Nezha Monitoring"

[Server]
other = "Servidores"

[Services]
other = "Servicios"

[Task]
other = "Tareas"

[Notification]
other = "Notificaciones"

[Settings]
other = "Configuraciones"

[Home]
other = "Inicio"

[BackToHomepage]
other = "Volver al Inicio"

[AdminPanel]
other = "Panel de Administración"

[Logout]
other = "Cerrar Sesión"

[Login]
other = "Iniciar Sesión"

[ConfirmLogout]
other = "¿Confirmar Cierre de Sesión?"

[AfterLoggingOutYouHaveToLoginAgain]
other = "Después de cerrar sesión, debe iniciar sesión nuevamente para continuar"

[Cancel]
other = "Cancelar"

[Confirm]
other = "Confirmar"

[AddScheduledTasks]
other = "Agregar Tareas Programadas"

[Name]
other = "Nombre"

[Scheduler]
other = "Plan"

[BackUp]
other = "Respaldo"

[3amDaily]
other = "(Diariamente a las 3 a.m.)"

[Command]
other = "Comandos"

[Coverage]
other = "Cobertura"

[IgnoreAllAndExecuteOnlyThroughSpecificServers]
other = "Ignorar todo, ejecutar solo a través de servidores específicos"

[AllIncludedOnlySpecificServersAreNotExecuted]
other = "Incluir todo, excepto servidores específicos"

[ExecuteByTriggerServer]
other = "Ejecutar en servidores con alarma"

[SpecificServers]
other = "Servidores Específicos"

[EnterIdAndNameToSearch]
other = "Ingrese ID/Nombre para buscar"

[NotificationMethodGroup]
other = "Grupo de Métodos de Notificación"

[PushSuccessMessages]
other = "Enviar el mensaje de éxito"

[TaskType]
other = "Tipo de Tarea"

[CronTask]
other = "Tarea Cron"

[TriggerTask]
other = "Tarea Disparadora"

[TheFormaOfTheScheduleIs]
other = "El formato del plan es:"

[SecondsMinutesHoursDaysMonthsWeeksSeeDetails]
other = "Segundos, Minutos, Horas, Días, Meses, Semanas - Ver detalles a"

[ScheduleExpressionFormat]
other = "Formato de Expresión de Cron"

[IntroductionOfCommands]
other = "Introducción de Comandos: Escriba comandos como en scripts shell/bat. Evite saltos de línea; conecte múltiples comandos con <code>&&</code> o <code>;</code>. Si no se encuentra un comando, verifique la variable de entorno <code>PATH</code>. En servidores <code>Linux</code>, antepóngale <code>source ~/.bashrc</code> a los comandos, o use rutas absolutas."

[AddMonitor]
other = "Agregar Monitor de Servicio"

[Blog]
other = "Blog"

[Target]
other = "Objetivo"

[Type]
other = "Tipo"

[SslExpirationOrChange]
other = "(Expiración o Cambio de SSL)"

[Duration]
other = "Intervalo de Solicitud"

[Seconds]
other = "Segundos"

[EnableFailureNotification]
other = "Habilitar Notificación de Fallo"

[FailureNotification]
other = "Notificación de Fallo"

[MaxLatency]
other = "Máxima Latencia (ms)"

[MinLatency]
other = "Mínima Latencia (ms)"

[EnableLatencyNotification]
other = "Habilitar Notificación de Latencia"

[LatencyNotification]
other = "Notificación de Latencia"

[IntroductionOfMonitor]
other = """
Para tipo <b>HTTP-GET</b>, ingrese URL (http/https, HTTPS también monitorea el certificado SSL);<br>
Para tipo <b>ICMP-Ping</b>, ingrese dominio/IP sin puerto;<br>
Para tipo <b>TCP-Ping</b>, ingrese dominio/IP + puerto: ejemplo.com:22"""

[AddNotificationMethod]
other = "Agregar Método de Notificación"

[Tag]
other = "Grupo de servidores"

[DoNotSendTestMessages]
other = "No Enviar Mensajes de Prueba"

[RequestMethod]
other = "Método de Solicitud"

[RequestType]
other = "Tipo de Solicitud"

[VerifySSL]
other = "Validar SSL"

[AddNotificationRule]
other = "Agregar Regla de Notificación"

[Rules]
other = "Reglas"

[NotificationTriggerMode]
other = "Modo de Disparo de Notificación"

[ModeAlwaysTrigger]
other = "Siempre Activar"

[ModeOnetimeTrigger]
other = "Activación Única"

[EnableTriggerTask]
other = "Habilitar Tarea Disparadora"

[FailTriggerTasks]
other = "Tareas Disparadas por Fallo"

[RecoverTriggerTasks]
other = "Tareas Disparadas por Recuperación"

[Enable]
other = "Habilitar"

[AddServer]
other = "Agregar Servidor"

[BatchEditServerGroup]
other = "Editar Grupo de Servidores en Lote"

[BatchDeleteServer]
other = "Eliminar Servidores en Lote"

[InputServerGroupName]
other = "Ingrese Nombre del Grupo de Servidores"

[ServerGroup]
other = "Grupos de Servidores"

[EinsteinLightspeed1]
other = "Einstein - Velocidad de luz 1"

[DisplayIndex]
other = "Índice de Visualización"

[TheLargerTheNumberTheHigherThePriority]
other = "A mayor número, mayor prioridad"

[Secret]
other = "Secreto"

[Note]
other = "Nota"

[PublicNote]
other = "Nota Pública"

[LinuxOneKeyInstall]
other = "Instalación Linux con Un Solo Clic"

[NoDomainAlert]
other = "Por favor, configure el dominio o IP del servidor del panel que no está conectado a la CDN en la página de configuración"

[PushSuccessfully]
other = "Envío Exitoso"

[LastExecution]
other = "Última Ejecución en"

[LastResult]
other = "Último Resultado"

[Administration]
other = "Administración"

[CoverAll]
other = "Cubrir Todo"

[IgnoreAll]
other = "Ignorar Todo"

[ByTrigger]
other = "Servidores con alarma"

[DeleteScheduledTask]
other = "Eliminar Tarea Programada"

[ConfirmToDeleteThisScheduledTask]
other = "¿Confirmar para eliminar esta Tarea Programada?"

[AccessDenied]
other = "Acceso Denegado"

[Use]
other = "Usar"

[AccountToLogin]
other = "Iniciar Sesión con Cuenta"

[SignUp]
other = "Registrarse"

[DontHaveAnAccount]
other = "¿No tiene una cuenta?"

[SSLCertificate]
other = "Certificados HTTP(S)/SSL"

[TCPPort]
other = "TCPing"

[DeleteService]
other = "Eliminar Servicio"

[ConfirmToDeleteThisService]
other = "¿Confirmar para eliminar este Servicio?"

[DeleteNotificationMethod]
other = "Eliminar Método de Notificación"

[ConfirmToDeleteThisNotificationMethod]
other = "¿Confirmar para eliminar este Método de Notificación?"

[ForceUpdate]
other = "Actualizar Ahora"

[SelectAll]
other = "Seleccionar Todo"

[VersionNumber]
other = "Número de Versión"

[OneKeyInstall]
other = "Instalación con Un Solo Clic"

[ClickToCopy]
other = "Hacer Clic para Copiar"

[DeleteServer]
other = "Eliminar Servidor"

[ConfirmToDeleteServer]
other = "¿Confirmar para eliminar este Servidor?"

[NoServerSelected]
other = "No hay Servidores Seleccionados"

[ExecutionResults]
other = "Resultados de Ejecución"

[SiteTitle]
other = "Título del Sitio"

[AdministratorList]
other = "Lista de Administradores"

[Theme]
other = "Tema de Frontend"

[CustomCodes]
other = "Códigos Personalizados (Incluye style y script)"

[CustomCodesDashboard]
other = "Custom Codes for Dashboard"

[AccessPassword]
other = "Contraseña de Acceso al Frontend"

[PanelServerDomainAndIP]
other = "Dominio/IP del Servidor del Panel sin CDN"

[IPChangeAlert]
other = "Notificación de Cambio de IP"

[AllIncludedOnlySpecificServersAreNotAlerted]
other = "Incluir Todo, Excepto Servidores Específicos"

[IgnoreAllOnlyAlertSpecificServers]
other = "Ignorar Todo, Alertar Solo Servidores Específicos"

[IgnoreAllRequestOnlyThroughSpecificServers]
other = "Ignorar Todo, Solicitar Solo a Través de Servidores Específicos"

[AllIncludedOnlySpecificServersAreNotRequest]
other = "Incluir Todo, Solo Los Servidores Específicos No Solicitan"

[ServerIDSeparatedByCommas]
other = "IDs de Servidores Separados por Comas"

[IPChangeNotificationTag]
other = "Enviar Alerta a Grupo de Notificación Específico"

[NotificationMessagesDoNotHideIP]
other = "Mostrar Dirección IP Completa en Mensajes de Notificación"

[Save]
other = "Guardar"

[ModifiedSuccessfully]
other = "Modificado con Éxito"

[TerminalConnectionTimeOutOrSessionEnded]
other = "Tiempo de Conexión del Terminal Agotado o Sesión Finalizada"

[TerminalConnectionFailed]
other = "Fallo en la Conexión del Terminal, Verifique la Configuración de Proxy Inverso de WebSocket en /terminal/*"

[Default]
other = "Predeterminado"

[Offline]
other = "Desconectado"

[Platform]
other = "Sistema"

[DiskUsed]
other = "Disco"

[MemUsed]
other = "Memoria"

[CpuUsed]
other = "CPU"

[Virtualization]
other = "Virtualización"

[SwapUsed]
other = "Swap"

[NetTransfer]
other = "Transferencia de Red"

[Load]
other = "Carga"

[ProcessCount]
other = "Cantidad de Procesos"

[ConnCount]
other = "Cantidad de Conexiones"

[BootTime]
other = "Tiempo de Arranque"

[LastActive]
other = "Última Actividad"

[Version]
other = "Versión"

[NetSpeed]
other = "Red"

[Uptime]
other = "Uptime"

[ServerIsOffline]
other = "El Servidor está Desconectado"

[Day]
other = "Días"

[RealtimeChannelEstablished]
other = "Canal en Tiempo Real Establecido"

[GetTheLatestMonitoringDataInRealTime]
other = "¡Ahora Puede Obtener los Últimos Datos de Monitoreo en Tiempo Real!"

[RealtimeChannelDisconnect]
other = "Canal en Tiempo Real Desconectado"

[CanNotGetTheLatestMonitoringDataInRealTime]
other = "¡No se Pueden Obtener los Últimos Datos de Monitoreo en Tiempo Real!"

[30DaysOnline]
other = "Disponibilidad de 30 Días"

[Details]
other = "Detalles"

[Status]
other = "Estado"

[Availability]
other = "Disponibilidad"

[AverageLatency]
other = "Latencia Promedio"

[CycleTransferStats]
other = "Estadísticas de Transferencia Periódica"

[From]
other = "Desde"

[To]
other = "Hasta"

[NextCheck]
other = "Próxima Verificación"

[CurrentUsage]
other = "Uso Actual"

[VerifyPassword]
other = "Verificar Contraseña"

[LightMode]
other = "Modo Claro"

[DarkMode]
other = "Modo Oscuro"

[FollowSystem]
other = "Seguir al Sistema"

[GridLayout]
other = "Diseño de Cuadrícula"

[ListLayout]
other = "Diseño de Lista"

[EnterPassword]
other = "Ingrese Contraseña"

[Location]
other = "Ubicación"

[Running]
other = "En Funcionamiento"

[UpNetTransfer]
other = "Red Ascendente"

[DownNetTransfer]
other = "Red Descendente"

[TotalUpNetTransfer]
other = "Total Ascendente"

[TotalDownNetTransfer]
other = "Total Descendente"

[WrongPassword]
other = "Contraseña Incorrecta"

[AnErrorEccurred]
other = "Ocurrió un Error"

[SystemError]
other = "Error del Sistema"

[NetworkError]
other = "Error de Red"

[ServicesStatus]
other = "Estado de los Servicios"

[ServersManagement]
other = "Gestión de Servidores"

[ServicesManagement]
other = "Gestión de Servicios"

[ScheduledTasks]
other = "Tareas Programadas"

[ApiManagement]
other = "Gestión de API"

[IssueNewApiToken]
other = "Emitir Nuevo Token"

[Token]
other = "Token"

[DeleteToken]
other = "Eliminar Token"

[ConfirmToDeleteThisToken]
other = "¿Confirmar para Eliminar este Token?"

[YouAreNotAuthorized]
other = "No Autorizado para esta Página"

[WrongAccessPassword]
other = "Contraseña de Acceso Incorrecta"

[Add]
other = "Agregar"

[Edit]
other = "Editar"

[AlarmRule]
other = "Reglas de Alarma"

[NotificationMethod]
other = "Método de notificación"

[Incident]
other = "Incidente"

[Resolved]
other = "Resuelto"

[StatusDown]
other = "Caído"

[StatusNoData]
other = "Sin Datos"

[StatusGood]
other = "Bueno"

[StatusLowAvailability]
other = "Baja Disponibilidad"

[ScheduledTaskExecutedSuccessfully]
other = "Tarea Programada Ejecutada con Éxito"

[ScheduledTaskExecutedFailed]
other = "Fallo en la Ejecución de la Tarea Programada"

[IPChanged]
other = "Cambio de IP"

[Transleft]
other = "Transferencia Restante"

[DashboardTheme]
other = "Tema del Panel de Administración"

[Info]
other = "Información"

[HideForGuest]
other = "Ocultar para Invitados"

[Menu]
other = "Menú"

[NetworkSpiter]
other = "Red"

[EnableShowInService]
other = "Mostrar en servicio"

[DDNS]
other = "DNS Dinámico"

[DDNSProfiles]
other = "Perfiles DDNS"

[AddDDNSProfile]
other = "Nuevo Perfil"

[EnableDDNS]
other = "Habilitar DDNS"

[EnableIPv4]
other = "IPv4 Activado"

[EnableIPv6]
other = "IPv6 Activado"

[DDNSDomain]
other = "Dominios"

[DDNSDomains]
other = "Dominios (separados por comas)"

[DDNSProvider]
other = "Proveedor DDNS"

[MaxRetries]
other = "Número máximo de intentos de reintento"

[DDNSAccessID]
other = "Credencial 1"

[DDNSAccessSecret]
other = "Credencial 2"

[DDNSTokenID]
other = "ID del Token"

[DDNSTokenSecret]
other = "Secreto del Token"

[WebhookURL]
other = "URL del Webhook"

[WebhookMethod]
other = "Método de Solicitud del Webhook"

[WebhookRequestType]
other = "Tipo de solicitud del Webhook"

[WebhookHeaders]
other = "Encabezados de Solicitud del Webhook"

[WebhookRequestBody]
other = "Cuerpo de Solicitud del Webhook"

[Feature]
other = "Característica"

[Template]
other = "Plantilla"

[Stat]
other = "Stat"

[Temperature]
other = "Temperatura"

[DisableSwitchTemplateInFrontend]
other = "Deshabilitar Cambio de Plantilla en Frontend"

[ServersOnWorldMap]
other = "Servidores en el mapa mundial"

[NAT]
other = "NAT traversal"

[LocalService]
other = "Servicio de red local"

[LocalServicePlaceholder]
other = "192.168.1.1:80 (con puerto)"

[BindHostname]
other = "Vincular nombre de host"

[NetworkSpiterList]
other = "Monitor de red"

[Refresh]
other = "Actualizar"

[CopyPath]
other = "Copiar ruta"

[Goto]
other = "Ir a"

[GotoHeadline]
other = "Ir a una carpeta"

[GotoGo]
other = "Ir"

[GotoClose]
other = "Cancelar"

[FMError]
other = "Agent devolvió un error, consulte la consola para obtener más detalles. Para abrir una nueva conexión, vuelva a abrir el FM."

[Remaining]
other = "Remaining"

[Lifetime]
other = "Lifetime"

[Price]
other = "Price"

[Expired]
other = "Expired"

[Days]
other = "d"

[CustomNameservers]
other = "Servidores DNS públicos personalizados para DDNS (separar con coma)"

[Plan]
other = "Plan"
