[NezhaMonitoring]
other = "哪吒監控"

[Server]
other = "伺服器"

[Services]
other = "服務"

[Task]
other = "任務"

[Notification]
other = "告警"

[Settings]
other = "設置"

[Home]
other = "首頁"

[BackToHomepage]
other = "返回前台"

[AdminPanel]
other = "管理後台"

[Logout]
other = "登出"

[Login]
other = "登入"

[ConfirmLogout]
other = "確定要登出嗎？"

[AfterLoggingOutYouHaveToLoginAgain]
other = "登出後需重新登入以繼續使用"

[Cancel]
other = "取消"

[Confirm]
other = "確認"

[AddScheduledTasks]
other = "新增計劃任務"

[Name]
other = "名稱"

[Scheduler]
other = "排程"

[BackUp]
other = "備份"

[3amDaily]
other = "(每天3點)"

[Command]
other = "命令"

[Coverage]
other = "覆蓋範圍"

[IgnoreAllAndExecuteOnlyThroughSpecificServers]
other = "忽略所有，僅通過特定伺服器執行"

[AllIncludedOnlySpecificServersAreNotExecuted]
other = "覆蓋所有，僅特定伺服器不執行"

[ExecuteByTriggerServer]
other = "由觸發告警的伺服器執行"

[SpecificServers]
other = "特定伺服器"

[EnterIdAndNameToSearch]
other = "輸入ID/名稱以搜尋"

[NotificationMethodGroup]
other = "通知群組"

[PushSuccessMessages]
other = "推送成功的訊息"

[TaskType]
other = "任務類型"

[CronTask]
other = "排程任務"

[TriggerTask]
other = "觸發任務"

[TheFormaOfTheScheduleIs]
other = "排程的格式為："

[SecondsMinutesHoursDaysMonthsWeeksSeeDetails]
other = "秒 分 時 天 月 星期，詳情見"

[ScheduleExpressionFormat]
other = "排程表達式格式"

[IntroductionOfCommands]
other = "命令說明：編寫命令時類似於 shell/bat 腳本。建議不要換行，多個命令可用 <code>&&</code> 或 <code>;</code> 連接，若出現命令無法找到的情況，可能是由於 <code>PATH</code> 環境變數配置問題。在 <code>Linux</code> 伺服器上，可在命令開頭加入 <code>source ~/.bashrc</code>，或使用命令的絕對路徑執行。"

[AddMonitor]
other = "新增監控"

[Blog]
other = "部落格"

[Target]
other = "目標"

[Type]
other = "類型"

[SslExpirationOrChange]
other = "(SSL到期、變更)"

[Duration]
other = "請求間隔"

[Seconds]
other = "秒"

[EnableFailureNotification]
other = "啟用故障通知"

[FailureNotification]
other = "故障通知"

[MaxLatency]
other = "最大延遲(ms)"

[MinLatency]
other = "最小延遲(ms)"

[EnableLatencyNotification]
other = "啟用延遲通知"

[LatencyNotification]
other = "延遲通知"

[IntroductionOfMonitor]
other = """
類型為 <b>HTTP-GET</b> 時輸入URL(帶 http/https, HTTPS協議的會順帶監控SSL證書)；<br>
類型為 <b>ICMP-Ping</b> 時輸入域名/IP，不帶端口；<br>
類型為 <b>TCP-Ping</b> 時輸入域名/IP + 端口號：example.com:22"""

[AddNotificationMethod]
other = "新增通知方式"

[Tag]
other = "分組"

[DoNotSendTestMessages]
other = "不發送測試訊息"

[RequestMethod]
other = "請求方式"

[RequestType]
other = "請求類型"

[VerifySSL]
other = "驗證SSL"

[AddNotificationRule]
other = "新增告警規則"

[Rules]
other = "規則"

[NotificationTriggerMode]
other = "通知觸發模式"

[ModeAlwaysTrigger]
other = "始終觸發"

[ModeOnetimeTrigger]
other = "單次觸發"

[EnableTriggerTask]
other = "啟用觸發任務"

[FailTriggerTasks]
other = "告警時觸發任務"

[RecoverTriggerTasks]
other = "恢復時觸發任務"

[Enable]
other = "啟用"

[AddServer]
other = "新增伺服器"

[BatchEditServerGroup]
other = "批量修改分組"

[BatchDeleteServer]
other = "批量刪除伺服器"

[InputServerGroupName]
other = "輸入分組名稱"

[ServerGroup]
other = "伺服器分組"

[EinsteinLightspeed1]
other = "愛因斯坦-光速1號"

[DisplayIndex]
other = "排序"

[TheLargerTheNumberTheHigherThePriority]
other = "越大越靠前"

[Secret]
other = "金鑰"

[Note]
other = "備註"

[PublicNote]
other = "公開備註"

[LinuxOneKeyInstall]
other = "Linux 一鍵安裝"

[NoDomainAlert]
other = "請先在設置頁面配置 未接入CDN的面板伺服器域名/IP"

[PushSuccessfully]
other = "推送成功"

[LastExecution]
other = "最近執行"

[LastResult]
other = "最後結果"

[Administration]
other = "管理"

[CoverAll]
other = "覆蓋所有"

[IgnoreAll]
other = "忽略所有"

[ByTrigger]
other = "觸發告警的伺服器"

[DeleteScheduledTask]
other = "刪除排程任務"

[ConfirmToDeleteThisScheduledTask]
other = "確認刪除此排程任務？"

[AccessDenied]
other = "訪問被拒絕"

[Use]
other = "使用"

[AccountToLogin]
other = "帳號登入"

[SignUp]
other = "註冊"

[DontHaveAnAccount]
other = "沒有帳號？"

[SSLCertificate]
other = "HTTP(S)/SSL證書"

[TCPPort]
other = "TCPing"

[DeleteService]
other = "移除服務"

[ConfirmToDeleteThisService]
other = "確認刪除此服務？"

[DeleteNotificationMethod]
other = "刪除通知方式"

[ConfirmToDeleteThisNotificationMethod]
other = "確認刪除此通知方式？"

[ForceUpdate]
other = "立即更新"

[SelectAll]
other = "全選"

[VersionNumber]
other = "版本號"

[OneKeyInstall]
other = "一鍵安裝"

[ClickToCopy]
other = "點擊複製"

[DeleteServer]
other = "刪除伺服器"

[ConfirmToDeleteServer]
other = "確認刪除伺服器？"

[NoServerSelected]
other = "當前沒有選中的伺服器"

[ExecutionResults]
other = "執行結果"

[SiteTitle]
other = "網站標題"

[AdministratorList]
other = "管理員列表"

[Theme]
other = "前台界面主題"

[CustomCodes]
other = "自定義代碼（包括 style 和 script）"

[CustomCodesDashboard]
other = "Custom Codes for Dashboard"

[AccessPassword]
other = "前台訪問密碼"

[PanelServerDomainAndIP]
other = "未接入CDN的面板伺服器域名/IP"

[IPChangeAlert]
other = "IP 變動通知"

[AllIncludedOnlySpecificServersAreNotAlerted]
other = "覆蓋所有，僅特定伺服器不提醒"

[IgnoreAllOnlyAlertSpecificServers]
other = "忽略所有，僅提醒特定伺服器"

[IgnoreAllRequestOnlyThroughSpecificServers]
other = "忽略所有，僅通過特定伺服器請求"

[AllIncludedOnlySpecificServersAreNotRequest]
other = "覆蓋所有，僅特定伺服器不請求"

[ServerIDSeparatedByCommas]
other = "伺服器ID 以逗號隔開"

[IPChangeNotificationTag]
other = "將提醒發送至指定通知分組"

[NotificationMessagesDoNotHideIP]
other = "通知信息中顯示完整IP地址"

[Save]
other = "保存"

[ModifiedSuccessfully]
other = "修改成功"

[TerminalConnectionTimeOutOrSessionEnded]
other = "Terminal 連接超時或會話已結束"

[TerminalConnectionFailed]
other = "Terminal 連接失敗，請檢查 /terminal/* 的 WebSocket 反向代理配置"

[Default]
other = "默認"

[Offline]
other = "已離線"

[Platform]
other = "系統"

[DiskUsed]
other = "硬碟"

[MemUsed]
other = "記憶體"

[CpuUsed]
other = "核心"

[Virtualization]
other = "虛擬化"

[SwapUsed]
other = "交換"

[NetTransfer]
other = "流量"

[Load]
other = "負載"

[ProcessCount]
other = "行程數"

[ConnCount]
other = "連接數"

[BootTime]
other = "啟動"

[LastActive]
other = "活動"

[Version]
other = "版本"

[NetSpeed]
other = "網速"

[Uptime]
other = "在線"

[ServerIsOffline]
other = "伺服器已離線"

[Day]
other = "天"

[RealtimeChannelEstablished]
other = "實時通道已建立"

[GetTheLatestMonitoringDataInRealTime]
other = "可以實時獲取最新監控數據啦"

[RealtimeChannelDisconnect]
other = "實時通道已斷開"

[CanNotGetTheLatestMonitoringDataInRealTime]
other = "無法實時獲取最新監控數據咯"

[30DaysOnline]
other = "近30天可用性"

[Details]
other = "詳情"

[Status]
other = "狀態"

[Availability]
other = "可用性"

[AverageLatency]
other = "平均回應時間"

[CycleTransferStats]
other = "周期性流量統計"

[From]
other = "起始"

[To]
other = "結束"

[NextCheck]
other = "下一次檢測"

[CurrentUsage]
other = "當前用量"

[VerifyPassword]
other = "驗證查看密碼"

[LightMode]
other = "亮色模式"

[DarkMode]
other = "暗色模式"

[FollowSystem]
other = "跟隨系統"

[GridLayout]
other = "網格佈局"

[ListLayout]
other = "列表佈局"

[EnterPassword]
other = "請輸入密碼"

[Location]
other = "位置"

[Running]
other = "運行中"

[UpNetTransfer]
other = "上行"

[DownNetTransfer]
other = "下行"

[TotalUpNetTransfer]
other = "總上行"

[TotalDownNetTransfer]
other = "總下行"

[WrongPassword]
other = "輸入的密碼錯誤"

[AnErrorEccurred]
other = "發生錯誤"

[SystemError]
other = "系統錯誤"

[NetworkError]
other = "網路錯誤"

[ServicesStatus]
other = "服務狀態"

[ServersManagement]
other = "伺服器管理"

[ServicesManagement]
other = "服務監控"

[ScheduledTasks]
other = "排程任務"

[ApiManagement]
other = "API 管理"

[IssueNewApiToken]
other = "生成Token"

[Token]
other = "Token"

[DeleteToken]
other = "刪除Token"

[ConfirmToDeleteThisToken]
other = "確認刪除Token"

[YouAreNotAuthorized]
other = "此頁面需要登入"

[WrongAccessPassword]
other = "訪問密碼錯誤"

[Add]
other = "新增"

[Edit]
other = "修改"

[AlarmRule]
other = "告警規則"

[NotificationMethod]
other = "通知方式"

[Incident]
other = "事件"

[Resolved]
other = "恢復"

[StatusDown]
other = "故障"

[StatusNoData]
other = "無數據"

[StatusGood]
other = "正常"

[StatusLowAvailability]
other = "低可用"

[ScheduledTaskExecutedSuccessfully]
other = "任務執行成功"

[ScheduledTaskExecutedFailed]
other = "任務執行失敗"

[IPChanged]
other = "IP變更"

[Transleft]
other = "剩餘流量"

[DashboardTheme]
other = "後台界面主題"

[Info]
other = "信息"

[HideForGuest]
other = "對遊客隱藏"

[Menu]
other = "菜單"

[NetworkSpiter]
other = "網路"

[EnableShowInService]
other = "在服務中顯示"

[DDNS]
other = "動態 DNS"

[DDNSProfiles]
other = "DDNS配置"

[AddDDNSProfile]
other = "新增配置"

[EnableDDNS]
other = "啟用 DDNS"

[EnableIPv4]
other = "啟用 DDNS IPv4"

[EnableIPv6]
other = "啟用 DDNS IPv6"

[DDNSDomain]
other = "DDNS 域名"

[DDNSDomains]
other = "域名（逗號分隔）"

[DDNSProvider]
other = "DDN S供應商"

[MaxRetries]
other = "最大重試次數"

[DDNSAccessID]
other = "DDNS 憑據 1"

[DDNSAccessSecret]
other = "DDNS 憑據 2"

[DDNSTokenID]
other = "令牌 ID"

[DDNSTokenSecret]
other = "令牌 Secret"

[WebhookURL]
other = "Webhook 地址"

[WebhookMethod]
other = "Webhook 請求方式"

[WebhookRequestType]
other = "Webhook 請求類型"

[WebhookHeaders]
other = "Webhook 請求頭"

[WebhookRequestBody]
other = "Webhook 請求體"

[Feature]
other = "功能"

[Template]
other = "主題"

[Stat]
other = "信息"

[Temperature]
other = "溫度"

[DisableSwitchTemplateInFrontend]
other = "禁止前台切換主題"

[ServersOnWorldMap]
other = "伺服器世界分布圖"

[NAT]
other = "NAT穿透"

[LocalService]
other = "內網服務"

[LocalServicePlaceholder]
other = "192.168.1.1:80(帶埠號)"

[BindHostname]
other = "綁定網域"

[NetworkSpiterList]
other = "網路監控"

[Refresh]
other = "重新整理"

[CopyPath]
other = "複製路徑"

[Goto]
other = "跳至"

[GotoHeadline]
other = "跳至資料夾"

[GotoGo]
other = "確定"

[GotoClose]
other = "取消"

[FMError]
other = "Agent 回傳了錯誤，請查看主控台獲取詳細資訊。要建立新連線，請重新開啟 FM。"

[Remaining]
other = "剩餘"

[Lifetime]
other = "永續"

[Price]
other = "價格"

[Expired]
other = "已到期"

[Days]
other = "天"

[CustomNameservers]
other = "自訂DDNS使用的公共DNS伺服器（逗號分隔）"

[Plan]
other = "套餐"
